[tool.poetry]
name = "pryml"
version = "0.1.0"
description = ""
authors = ["Justin M Bacher"]
license = "LGPL V3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
